linters:
  enable:
    - goimports      # Checks for import formatting
    - govet          # Reports suspicious constructs
    - staticcheck    # Go static analysis tool
    - errcheck       # Checks for unchecked errors
    - gosimple       # Suggests code simplifications
    - ineffassign    # Detects unused variable assignments
    - unused         # Checks for unused constants, variables, functions and types
    - misspell       # Checks for commonly misspelled English words

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck   # Don't require error checks in tests
  exclude-dirs:
    - vendor/
    - node_modules/

run:
  deadline: 5m
  tests: true

output:
  formats: 
    - format: colored-line-number 